In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded = files.upload()

Saving gender-prediction.csv to gender-prediction.csv


In [3]:
import io
df = pd.read_csv(io.BytesIO(uploaded['gender-prediction.csv']))
print(df)

    height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
75      65      99    no       short         39   yes     green  female
76      61      98    no       short         37    no     brown  female
77      67     119   yes       short         40    no     black    male
78      70     190   yes      medium         43    no      gray    male
79      62     142   yes        long         37    no      blue  female

[80 rows x 8 columns]


In [4]:
df.head(5)

height  weight beard hair_length  shoe_size scarf eye_color  gender
0      71     176   yes       short         44    no     black    male
1      68     165    no        bald         41    no     black    male
2      62     132    no      medium         37   yes      blue  female
3      65     138    no        long         38    no      gray  female
4      70     197   yes      medium         43    no      gray    male

In [5]:
from sklearn.preprocessing import LabelEncoder


In [6]:
le = LabelEncoder()
b = le.fit_transform(df['beard'])
b


array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1])

In [7]:
le.classes_

array(['no', 'yes'], dtype=object)

In [8]:
h = le.fit_transform(df['hair_length'])
h

array([3, 0, 2, 1, 2, 3, 0, 3, 3, 2, 1, 3, 2, 1, 2, 3, 3, 1, 1, 2, 2, 2,
       3, 2, 2, 2, 2, 2, 1, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 3,
       0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 1, 1, 0,
       1, 3, 2, 3, 1, 2, 2, 1, 1, 3, 3, 3, 2, 1])

In [9]:
s = le.fit_transform(df['scarf'])
s

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [10]:
e = le.fit_transform(df['eye_color'])
e

array([0, 0, 1, 3, 3, 0, 2, 2, 4, 3, 3, 3, 0, 3, 0, 1, 0, 4, 3, 4, 0, 0,
       0, 3, 2, 2, 0, 4, 1, 3, 2, 3, 3, 0, 2, 2, 4, 0, 3, 4, 3, 0, 0, 2,
       0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 3, 2, 2, 2, 2, 2, 4, 3, 0,
       4, 0, 0, 0, 2, 0, 2, 3, 4, 4, 2, 0, 3, 1])

In [11]:
data = df.drop("beard", axis= 'columns')
data = df.drop("hair_length", axis= 'columns')
data = df.drop("scarf", axis= 'columns')
data = df.drop("eye_color", axis= 'columns')
data["beard"] = b
data["hair_length"] = h
data["scarf"] = s
data["eye_color"] = e
data

height  weight  beard  hair_length  shoe_size  scarf  gender  eye_color
0       71     176      1            3         44      0    male          0
1       68     165      0            0         41      0    male          0
2       62     132      0            2         37      1  female          1
3       65     138      0            1         38      0  female          3
4       70     197      1            2         43      0    male          3
..     ...     ...    ...          ...        ...    ...     ...        ...
75      65      99      0            3         39      1  female          4
76      61      98      0            3         37      0  female          2
77      67     119      1            3         40      0    male          0
78      70     190      1            2         43      0    male          3
79      62     142      1            1         37      0  female          1

[80 rows x 8 columns]

In [12]:
#Here only excluding the 'gender' and taking the remaining as inputs
X = data.drop("gender", axis= 'columns')
#Only taking 'gender' as the output
Y = data['gender']

#Here taking remaining attributes except beard, scarf and gender for input and only gender for output
#X = data.drop(["beard", "scarf", "gender"], axis = 'columns')
#Y = Y = data['gender']

X



height  weight  beard  hair_length  shoe_size  scarf  eye_color
0       71     176      1            3         44      0          0
1       68     165      0            0         41      0          0
2       62     132      0            2         37      1          1
3       65     138      0            1         38      0          3
4       70     197      1            2         43      0          3
..     ...     ...    ...          ...        ...    ...        ...
75      65      99      0            3         39      1          4
76      61      98      0            3         37      0          2
77      67     119      1            3         40      0          0
78      70     190      1            2         43      0          3
79      62     142      1            1         37      0          1

[80 rows x 7 columns]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.20, random_state=42)

In [14]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()
rf.fit(X_train,y_train)
predictions = rf.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score, f1_score
#print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

[[7 0]
 [0 9]]


In [15]:
#Support Vector Machine Classifier
from sklearn.svm import SVC
svm= SVC()
svm.fit(X_train,y_train)
predictions = svm.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score, f1_score
#print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

[[5 2]
 [4 5]]


In [52]:
#MLP Classifier
from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier()
mlp.fit(X_train,y_train)
predictions = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score, f1_score
#print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

[[5 2]
 [1 8]]


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [98]:
#Decision Tree Classifier with Monte Carlo (shuffle-split) Cross Validation
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
from sklearn.model_selection import ShuffleSplit,cross_val_score
shuffle_split=ShuffleSplit(test_size=0.33,n_splits=10)
scores=cross_val_score(dt,X_test,predictions,cv=shuffle_split)
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score, f1_score
print(classification_report(y_test,predictions))
#print(confusion_matrix(y_test,predictions))
#print("Average Cross Validation score :{}".format(scores.mean()))


              precision    recall  f1-score   support

      female       1.00      1.00      1.00         7
        male       1.00      1.00      1.00         9

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16



In [189]:
#Decision Tree Classifier with Leave P-Out Cross Validation
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
from sklearn.model_selection import LeavePOut,cross_val_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score, f1_score
#lpo=LeavePOut(p=5)
#lpo.get_n_splits(X)
#dt = DecisionTreeClassifier(max_depth=5)
#score=cross_val_score(dt,X,Y,cv=lpo)
#print(classification_report(y_test,predictions))
#print(confusion_matrix(y_test,predictions))
#print("Average Cross Validation score :{}".format(score.mean()))

In [108]:
from google.colab import files
uploaded = files.upload()


Saving gender-prediction-after5instances.csv to gender-prediction-after5instances.csv


In [109]:
import io
q4data = pd.read_csv(io.BytesIO(uploaded['gender-prediction-after5instances.csv']))
print(q4data)

    height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
80      75     162   yes      medium         42    no     black    male
81      85     176   yes       short         37    no      blue    male
82     120     175   yes       short         36    no      gray    male
83      57     143    no        long         38    no     black  female
84      50     159    no        long         43   yes     black  female

[85 rows x 8 columns]


In [119]:
q4data.head(5)

height  weight beard hair_length  shoe_size scarf eye_color  gender
0      71     176   yes       short         44    no     black    male
1      68     165    no        bald         41    no     black    male
2      62     132    no      medium         37   yes      blue  female
3      65     138    no        long         38    no      gray  female
4      70     197   yes      medium         43    no      gray    male

In [130]:
be = le.fit_transform(q4data['beard'])
be

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [131]:
ha = le.fit_transform(q4data['hair_length'])
ha

array([3, 0, 2, 1, 2, 3, 0, 3, 3, 2, 1, 3, 2, 1, 2, 3, 3, 1, 1, 2, 2, 2,
       3, 2, 2, 2, 2, 2, 1, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 3,
       0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 1, 1, 0,
       1, 3, 2, 3, 1, 2, 2, 1, 1, 3, 3, 3, 2, 1, 2, 3, 3, 1, 1])

In [132]:
sc = le.fit_transform(q4data['scarf'])
sc

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [133]:
ey = le.fit_transform(q4data['eye_color'])
ey

array([0, 0, 1, 3, 3, 0, 2, 2, 4, 3, 3, 3, 0, 3, 0, 1, 0, 4, 3, 4, 0, 0,
       0, 3, 2, 2, 0, 4, 1, 3, 2, 3, 3, 0, 2, 2, 4, 0, 3, 4, 3, 0, 0, 2,
       0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 3, 2, 2, 2, 2, 2, 4, 3, 0,
       4, 0, 0, 0, 2, 0, 2, 3, 4, 4, 2, 0, 3, 1, 0, 1, 3, 0, 0])

In [134]:
data = q4data.drop("beard", axis= 'columns')
data = q4data.drop("hair_length", axis= 'columns')
data = q4data.drop("scarf", axis= 'columns')
data = q4data.drop("eye_color", axis= 'columns')


In [135]:
data["beard"] = be
data["hair_length"] = ha
data["scarf"] = sc
data["eye_color"] = ey
data


height  weight  beard  hair_length  shoe_size  scarf  gender  eye_color
0       71     176      1            3         44      0    male          0
1       68     165      0            0         41      0    male          0
2       62     132      0            2         37      1  female          1
3       65     138      0            1         38      0  female          3
4       70     197      1            2         43      0    male          3
..     ...     ...    ...          ...        ...    ...     ...        ...
80      75     162      1            2         42      0    male          0
81      85     176      1            3         37      0    male          1
82     120     175      1            3         36      0    male          3
83      57     143      0            1         38      0  female          0
84      50     159      0            1         43      1  female          0

[85 rows x 8 columns]

In [136]:
#Here only excluding the 'gender' and taking the remaining as inputs
X = data.drop("gender", axis= 'columns')
#Only taking 'gender' as the output
Y = data['gender']
X

height  weight  beard  hair_length  shoe_size  scarf  eye_color
0       71     176      1            3         44      0          0
1       68     165      0            0         41      0          0
2       62     132      0            2         37      1          1
3       65     138      0            1         38      0          3
4       70     197      1            2         43      0          3
..     ...     ...    ...          ...        ...    ...        ...
80      75     162      1            2         42      0          0
81      85     176      1            3         37      0          1
82     120     175      1            3         36      0          3
83      57     143      0            1         38      0          0
84      50     159      0            1         43      1          0

[85 rows x 7 columns]

In [137]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.33, random_state=42)

In [138]:
#Gaussian Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
gNB = GaussianNB()

In [141]:
gNB.fit(X_train,y_train)

GaussianNB()

In [148]:
#Selecting the newly added 5 instances for the purpose of testing
testdf = X.loc[80:84, :]
testdf

height  weight  beard  hair_length  shoe_size  scarf  eye_color
80      75     162      1            2         42      0          0
81      85     176      1            3         37      0          1
82     120     175      1            3         36      0          3
83      57     143      0            1         38      0          0
84      50     159      0            1         43      1          0

In [169]:
#Evaluating the model using the newly added instances
prediction = gNB.predict(testdf)
prediction


array(['male', 'male', 'male', 'female', 'female'], dtype='<U6')

In [180]:
#Seperating the Output instances of the Gender attribute that coincide with the newly added 5 instances
sep = Y.loc[80:84]
sep

80      male
81      male
82      male
83    female
84    female
Name: gender, dtype: object

In [181]:
#Accuracy
model_acc = accuracy_score(sep, prediction)*100
print(model_acc)

100.0


In [187]:
#Precision
from sklearn import metrics
gNBcrep = metrics.classification_report(sep, prediction)
print(gNBcrep)

              precision    recall  f1-score   support

      female       1.00      1.00      1.00         2
        male       1.00      1.00      1.00         3

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

